# ---------------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------------
spring:
   application:
     name: Killrvideo-API-GraphQL
server:
  port: 8083
  servlet:
    context-path: /gql

# ---------------------------------------------------------------------------------
# Cassandra
# ---------------------------------------------------------------------------------
dse:
   contactPoints: 127.0.0.1
   port: 9042
   localdc: Cassandra
   keyspace: killrvideo
   username: 
   password:
   